version: "3.9"
   
services:
  web:
    build: .
    command: dotnet WebProject.dll --server.urls http://localhost:80;https://localhost:443
    ports:
      - "8000:80"
      - "4430:443"
    volumes:
      - .:/code