version: "3.3"
   
services:
  web:
    build: .
    command: dotnet WebProject.dll --server.urls http://localhost:80;https://localhost:443
    ports:
      - "8000:80"
      - "4430:443"
    environment:
      - "AppDbName=${DB_NAME}"
      - "DbPass=${DB_PASS}"
      - "DbUser=${DB_USER}"
    volumes:
      - .:/code
    networks:
      - webapp-network
    depends_on:
      - postgres
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_USER=${DB_USER}"
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge